apiVersion: v2
name: jupyter-neurohackademy-org
description: A Helm chart to install all parts that make up the hub.neurohackademy.org deployment.
type: application
version: 0.1.0

dependencies:
  # JupyterHub
  # ArtifactHub:   https://artifacthub.io/packages/helm/jupyterhub/jupyterhub
  # Source code:   https://github.com/jupyterhub/zero-to-jupyterhub-k8s
  # App changelog: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/main/CHANGELOG.md
  #
  - name: jupyterhub
    version: 1.0.1
    repository: https://jupyterhub.github.io/helm-chart/

  # Prometheus for collection of metrics.
  # ArtifactHub:   https://artifacthub.io/packages/helm/prometheus-community/prometheus
  # Source code:   https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
  # App changelog: https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md
  #
  - name: prometheus
    version: 14.3.0
    repository: https://prometheus-community.github.io/helm-charts
    tags:
      - metrics

  # Grafana for dashboarding of metrics.
  # ArtifactHub:   https://artifacthub.io/packages/helm/grafana/grafana
  # Source code:   https://github.com/grafana/helm-charts/tree/main/charts/grafana
  # App changelog: https://github.com/grafana/grafana/blob/main/CHANGELOG.md
  #
  - name: grafana
    version: 6.13.5
    repository: https://grafana.github.io/helm-charts
    tags:
      - metrics
