jupyterhub:
    config:
        GitHubOAuthenticator:
            client_id: ENC[AES256_GCM,data:JkXgEZUy3hJSIWEaz3CNY4pQf2E=,iv:TOr9l502xDudyQjKq4LQftTG696TLrUxP5WmteeUaG8=,tag:bCjFcq8Cbz16eMFuOD8e7Q==,type:str]
            client_secret: ENC[AES256_GCM,data:ZoJedIrZhUBy5eZDHHSikjkDMPT2gZaMHWmfJFg0yKPlmqTy9C0ygw==,iv:QIaHGZyBvthjl3nSPfY6EsBQRo6kqKjbpR+Zi05deNo=,tag:gaxMeWlygtSI60/IYl/TQA==,type:str]
            oauth_callback_url: ENC[AES256_GCM,data:mW++p6KVknf8nSUJY06Y73/c1rUyYfOOvheTFtB/uU+CHC+wAdjnCX886h695aL9QQ==,iv:g3rWb/33EbG4Ro7z1pqywxVKSArATHJZGVuOjV/Btio=,tag:/ZWcd8EP/cTPt6NyjozZgQ==,type:str]
        JupyterHub:
            authenticator_class: ENC[AES256_GCM,data:xeIS8zdd,iv:3e4mN8gLtnfWFnSppAqsH1ttTpdMyOcBdN3gyxbeCKc=,tag:JYwr08LhYILS8v8kRT/QGg==,type:str]
grafana:
    adminUser: ENC[AES256_GCM,data:PjjjlT4=,iv:5xx3VXvaBYuXB/uhSTpzJWcCVANsnwZfhIs0B+/po/4=,tag:tSic6ZvMstFPE2SySb/sfA==,type:str]
    adminPassword: ENC[AES256_GCM,data:5oBCugghr4n0iik2n82aX0U=,iv:4ww3kgIkVhBDAr+wwCsZqnPpJVj8UHiZ3Tz65nmjUCo=,tag:sqHP2MAOcoJS+q0c9IkJqg==,type:str]
    grafana.ini:
        security:
            cookie_secure: ENC[AES256_GCM,data:64w+wg==,iv:qdvWabPcx2nCZ7qLoqrFxmLAOMXOU+UbD+FSgNSOjrw=,tag:2QGydcLPeBoYUhp4bOfVGw==,type:bool]
            secret_key: ENC[AES256_GCM,data:9ZuVBhROKZw7RQUpE8t64SDtzwnZAEzzPNTYXORWCHd5fC1NGnhvBw==,iv:c2SamaDYBdVE7TtAXW7+dOiPsmnHr3TZ2l0iNaeBORE=,tag:wvVtSprKxoWJtbbBr7b8Zw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/neurohackademy/locations/global/keyRings/nh/cryptoKeys/main
          created_at: "2021-06-29T07:49:40Z"
          enc: CiQAbsR6i3ZQRg7ZCFZhjFaKDjweprS03AqebrpnlkEOeDfRxwgSSQANoMcWG5UKOHUhbUbnO/wRUMfEeKTcGuHy6dxSI3tc9ilcLpPHqtvWAaiKH0IVeDCukl/s5EJCAjZoZoKG0AEjOSEP+gWOObw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-29T07:53:01Z"
    mac: ENC[AES256_GCM,data:LJaZkgCmdq01KDlGR1kGmKVh/3VUDtEsYx5vKFzVi/iCmoUKLlfC9Ovlhmkf88bD/yhN9uIRc4y5mzzZVA5UJeMozU1hSRU6mU2RZHvHjxUjJ/sBodqkv/u3Okgi3Op0YQwiwRA3LeG7R8Yyo8IKiRJvK6tPaAanetd+xCq77cc=,iv:MmCq3vs1J8QiPi1lCzshTQJQUQTDYNRCRUDGTM55gUE=,tag:0KEQgkiY0ZVg7hnAIHqaaA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
